# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Edit_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(787, 600)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(280, 30, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(40, 100, 721, 371))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.ok_but = QtWidgets.QPushButton(Form)
        self.ok_but.setGeometry(QtCore.QRect(660, 510, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ok_but.setFont(font)
        self.ok_but.setObjectName("ok_but")
        self.cancel_but = QtWidgets.QPushButton(Form)
        self.cancel_but.setGeometry(QtCore.QRect(500, 510, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cancel_but.setFont(font)
        self.cancel_but.setObjectName("cancel_but")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Edit Coffee Info"))
        self.ok_but.setText(_translate("Form", "OK"))
        self.cancel_but.setText(_translate("Form", "Отмена"))
