# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(687, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 20, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 80, 641, 371))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.edit_but = QtWidgets.QPushButton(self.centralwidget)
        self.edit_but.setGeometry(QtCore.QRect(20, 480, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.edit_but.setFont(font)
        self.edit_but.setObjectName("edit_but")
        self.add_but = QtWidgets.QPushButton(self.centralwidget)
        self.add_but.setGeometry(QtCore.QRect(170, 480, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.add_but.setFont(font)
        self.add_but.setObjectName("add_but")
        self.reset_but = QtWidgets.QPushButton(self.centralwidget)
        self.reset_but.setGeometry(QtCore.QRect(550, 480, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.reset_but.setFont(font)
        self.reset_but.setObjectName("reset_but")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 687, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Coffee display"))
        self.edit_but.setText(_translate("MainWindow", "Изменить"))
        self.add_but.setText(_translate("MainWindow", "Добавить"))
        self.reset_but.setText(_translate("MainWindow", "Обновить"))
